//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=16-00362\\SQLEXPRESS;AttachDbFilename=\"C:\\Program Files\\Microsoft SQL " +
            "Server\\MSSQL12.SQLEXPRESS\\MSSQL\\DATA\\CRM.mdf\";Integrated Security=True")]
        public string CRMConnectionString {
            get {
                return ((string)(this["CRMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=16-00362\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\CRM.mdf;Integrat" +
            "ed Security=True")]
        public string CRMConnectionString1 {
            get {
                return ((string)(this["CRMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=16-00362\\SQLEXPRESS;AttachDbFilename=\"C:\\Program Files\\Microsoft SQL " +
            "Server\\MSSQL12.SQLEXPRESS\\MSSQL\\DATA\\ncrm.mdf\";Integrated Security=True")]
        public string ncrmConnectionString {
            get {
                return ((string)(this["ncrmConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=16-00362\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\ncrm.mdf;Integra" +
            "ted Security=True")]
        public string ncrmConnectionString1 {
            get {
                return ((string)(this["ncrmConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=16-00362\\SQLEXPRESS;AttachDbFilename=\"C:\\Program Files\\Microsoft SQL " +
            "Server\\MSSQL12.SQLEXPRESS\\MSSQL\\DATA\\tas.mdf\";Integrated Security=True")]
        public string tasConnectionString {
            get {
                return ((string)(this["tasConnectionString"]));
            }
        }
    }
}
